### ISSUE TITLE
Flaky Not render execution time on osx with error code 1

### ISSUE THREAD

**Issue by khru** [TypedDevs/bashunit#181] opened 2023-10-13 07:44 UTC
#### Summary

I run the test and everything it's ok.

I add 2 test that should fail for example:
```bash
function test_successful_assert_string_starts_with() {
  assert_empty "$(assert_string_starts_with "ho" "house")"
}

function test_unsuccessful_assert_string_starts_with() {
  assert_equals\
    "$(console_results::print_failed_test\
      "Unsuccessful assert string starts with" "pause" "to not start with" "hou")"\
    "$(assert_string_starts_with "hou" "pause")"
}
```

the output of the test failing is:
```
tests/unit/assert_test.sh: línea 211: assert_string_starts_with: orden no encontrada
✗ Failed: Unsuccessful assert string starts with
    Expected '✗ Failed: Unsuccessful assert string starts with
    Expected 'pause'
    to not start with 'hou''
    but got ''
✓ Passed: Unsuccessful assert successful code
✓ Passed: Unsuccessful return assert exit code
Running tests/unit/console_results_test.sh
✗ Failed: Not render execution time on osx with error code 1
```

As you may see, there is a test that should NOT be failing but it is:

```
✗ Failed: Not render execution time on osx with error code 1
```
![bug](https://github.com/TypedDevs/bashunit/assets/6353105/db56569f-8ed5-49a7-a531-0a3b7dae5773)

**Comment by khru** [comment] 2023-10-13 13:27
```
╰─ ./bashunit ./tests --simple
.................../tests/unit/assert_test.sh: línea 226: kasjdhfkjasdhf: orden no encontrada
✗ Failed: Asdfasdf
    Expected 'to not be empty'
    but got ''
................................
..✗ Failed: Not render execution time on osx with error code 1
................................................
...............................................
Tests:      147 passed, 2 failed, 149 total
Assertions: 194 passed, 1 failed, 195 total
Some tests failed
Time taken: 8487 ms

```

**Comment by Chemaclass** [comment] 2024-09-22 15:07
I cannot reproduce this bug; I believe it was already fixed, so I closed this issue. 
 
![Screenshot 2024-09-22 at 17 06 27](https://github.com/user-attachments/assets/53f60658-f388-46dc-8483-ea203f4ef193)

**Closed by Chemaclass** 2024-09-22 15:07 UTC
Labels: bug
